# -*- coding: utf-8 -*-
"""PINGALA_2.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lXbvj_t3xUgjUOucL3ukTq9eUGJ2tX_b
"""

from matplotlib import pyplot as plt
import numpy as np

x = [1, 1]
for i in range(23): x.append(x[-1] + x[-2])
y = np.add(x[:23], x[2:])
plt.stem(range(23), y, use_line_collection = 'True')
plt.grid()
plt.xlabel('$n$')
plt.ylabel('$y(n)$')
plt.tight_layout()