# -*- coding: utf-8 -*-
"""PINGALA_2.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M1Xl292YnAbnK41qrYMluVyc_Zi1Boyg
"""

from matplotlib import pyplot as plt

x = [1, 1]
for i in range(23): x.append(x[-1] + x[-2])
plt.stem(range(len(x)), x, use_line_collection='True')
plt.grid()
plt.xlabel('$n$')
plt.ylabel('$x(n)$')
plt.tight_layout()